{
 "title": "Wasimoff",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Connected Providers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wasimoff_conn_providers{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "wasimoff_conn_providers_workers{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "wasimoff_tasks_throughput{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "gc_duration q={{ quantile }}"
    }
   ]
  },
  {
   "title": "Threads and Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "go_sched_gomaxprocs_threads{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "go_threads{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  }
 ]
}